apiVersion: v1
kind: Service
metadata:
  name: calendarapp
  labels:
    app: calendarapp
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: calendarapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calendarapp-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calendarapp
        version: v1
    spec:
      containers:
      - name: calendarapp
        image: istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calendarapp-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calendarapp
        version: v2
    spec:
      containers:
      - name: calendarapp
        image: istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: calendarapp-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: calendarapp
spec:
  hosts:
  - "*"
  gateways:
  - calendarapp-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: calendarapp
        port:
          number: 5000
