apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: testspace
spec:
  ports:
    - name: tcp
      nodePort: 31010
      port: 9000
      targetPort: 9000
      protocol: TCP
  type: NodePort
  selector:
    app: userservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: testspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      annotations:
      labels:
        app: userservice
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "9000"
          image: rmohammad/userservice:4
          name: userservice
          ports:
            - containerPort: 9000
              name: grpc
          resources:
            requests:
              cpu: 100m
