apiVersion: v1
kind: Namespace
metadata:
  name: testspace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: testspace
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: testspace
spec:
  ports:
    - name: tcp
      nodePort: 31009
      port: 9092
      targetPort: 9092
      protocol: TCP
  type: NodePort
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: testspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      annotations:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
          image: rmohammad/kafka-server:1
          name: kafka
          ports:
            - containerPort: 8080
              name: grpc
          resources:
            requests:
              cpu: 100m
      serviceAccountName: kafka
