apiVersion: v1
kind: Namespace
metadata:
  name: testspace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: time
  namespace: testspace
---
apiVersion: v1
kind: Service
metadata:
  name: time
  namespace: testspace
spec:
  ports:
    - name: tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: time
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time
  namespace: testspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: time
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
          image: rmohammad/time:1
          name: time
          ports:
            - containerPort: 8080
              name: grpc
          resources:
            requests:
              cpu: 100m
      serviceAccountName: time
