apiVersion: v1
kind: Namespace
metadata:
  name: testspace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting
  namespace: testspace
---
apiVersion: v1
kind: Service
metadata:
  name: greeting
  namespace: testspace
spec:
  ports:
    - name: tcp
      nodePort: 31006
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: greeting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  namespace: testspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      annotations:
      labels:
        app: greeting
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
          image: rmohammad/greeting:4
          name: greeting
          ports:
            - containerPort: 8080
              name: grpc
          resources:
            requests:
              cpu: 100m
      serviceAccountName: greeting
