apiVersion: v1
kind: Namespace
metadata:
  name: testspace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-producer-consumer
  namespace: testspace
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-consumer
  namespace: testspace
spec:
  ports:
    - name: tcp
      nodePort: 31008
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: kafka-producer-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-consumer
  namespace: testspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-consumer
  template:
    metadata:
      annotations:
      labels:
        app: kafka-producer-consumer
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
          image: rmohammad/kafka-producer-consumer:5
          name: kafka-producer-consumer
          ports:
            - containerPort: 8080
              name: grpc
          resources:
            requests:
              cpu: 100m
      serviceAccountName: kafka-producer-consumer
