apiVersion: v1
kind: Namespace
metadata:
  name: testspace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calendarapp
  namespace: testspace
---
apiVersion: v1
kind: Service
metadata:
  name: calendarapp
  namespace: testspace
spec:
  ports:
    - name: tcp
      nodePort: 31008
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: calendarapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendarapp
  namespace: testspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendarapp
  template:
    metadata:
      annotations:
      labels:
        app: calendarapp
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
          image: rmohammad/calendarapp:3
          name: calendarapp
          ports:
            - containerPort: 8080
              name: grpc
          resources:
            requests:
              cpu: 100m
      serviceAccountName: calendarapp
