apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: testspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      annotations:
      labels:
        app: userservice
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "9012"
          image: rmohammad/kafkaclient:4
          name: userservice
          ports:
            - containerPort: 9012
              name: grpc
          resources:
            requests:
              cpu: 100m
